#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ "$3" == 1 ]; then  # branch checkout only (not file checkout)
    # install deps
    pnpm deps:install
    # remove local branches that have been deleted on remote
    git fetch -p
    pnpx git-removed-branches -p -f
fi
